### PR TITLE
fix: issue #74 use local timezone

### LINKED ISSUE #74: cron job times are interpreted as UTC timezone
When I define a job with cron interval then the resulting execution times seem to be in UTC timezone. Is it possible to use local timezone?

### PR DESCRIPTION
**Pull request by snrmwg**
Use local timezone for jobs created with cron pattern or intervals written as human-friendly time representations.

Fixes #74.

### CODE REVIEW

**Comment by shadowgate15** [comment]
you would also need to add to job-builder.js and job-utils.js.

it also might be good to have this as an option in config with the default being local tz.

**Comment by snrmwg** [comment]
@shadowgate15 why? For my newly added tests the one place to fix seems to be enough. Could you provide additional tests that make clear the other places also need the extension?

And the broken build is a different test that also breaks the PR #75 currently.

**Comment by shadowgate15** [comment]
if anything, it isn't needed in index, since it is only used to schedule intervals and timeouts. In job-builder, it is used to create a schedule which is then used to set timeouts and intervals. I believe job-utils, uses it similarly.

**Comment by niftylettuce** [comment]
I'll defer to you @shadowgate15 and @naz to merge/review

File: test/test.js [hunk 1]
```diff
@@ -289,6 +289,41 @@ test('fails if cron pattern is invalid', (t) => {
...
+  const bree = new Bree({
+    root,
+    jobs: [{ name: 'basic', cron: '0 18 * * *' }]
+  });
+
+  const clock = FakeTimers.install({ now: Date.now() });
+  bree.start('basic');
+  bree.on('worker created', () => {
+    const now = new Date(clock.now);
+    t.is(now.getHours(), 18);
```
Comment (shadowgate15) [inline test/test.js:303]: let's change this to the timezone offset instead, so that we are testing explicitly what we want instead of an after effect. you should be able to use `now.getTimezoneOffset()`

**Comment by snrmwg** [comment]
Anything I can do to speedup process?

File: test/test.js (hunk 1 above)
Comment (shadowgate15) [reply test/test.js:303]: want to be testing the actual offset not just what the hours say.

**Comment by shadowgate15** [comment]
does it still work correctly when you add a new job after bree has been created?

File: test/test.js (hunk 1 above)
Comment (snrmwg) [reply test/test.js:308]: Ok, I added the offset check in the tests.

**Review by snrmwg — COMMENTED** [review]
> does it still work correctly when you add a new job after bree has been created?

I added another test to verify your scenario ("add > job created with cron string is using local timezone") and it is also green.

**Comment by snrmwg** [comment]
> if anything, it isn't needed in index, since it is only used to schedule intervals and timeouts. In job-builder, it is used to create a schedule which is then used to set timeouts and intervals. I believe job-utils, uses it similarly.

I have done it in index because it is the first place where `later` is used. In NodeJs each call of `require('@breejs/later')` will return the same instance. But I have moved the config call now to job-utils. Behaviour stays the same, my newly added tests are still green.

**Comment by shadowgate15** [comment]
Thanks for all the work @snrmwg!

**Comment by snrmwg** [comment]
> Thanks for all the work @snrmwg!

My pleasure!  Looking forward to the next release of breejs. @shadowgate15

**Comment by niftylettuce** [comment]
v5.0.0 released https://github.com/breejs/bree/releases/tag/v5.0.0 🎉 you all rock.  thank you @shadowgate15 et all
